### ISSUE TITLE
What is the albedo image？

### ISSUE THREAD

**Issue by yuqiu1233** [degawong/asff#1]
@degawong hi，thanks for your great working! I'm confused about albedo image.Can you tell me what it is?

**Comment by degawong** [comment]
i use this network for the relighting task, so the albedo image is human face albedo image. be sure use your specific image match with your own task.

**Comment by yuqiu1233** [comment]
> i use this network for the relighting task, so the albedo image is human face albedo image. be sure use your specific image match with your own task.

ok, I get it,thanks for your reply.
